spring:
  application:
    name: spring-cloud-service-provider
  cloud:
    zookeeper:
      connect-string: localhost:2181
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

# custom mongo configuration
data:
  mongo:
    test:
      uri: mongodb://127.0.0.1:27017/test?readpreference=secondaryPreferred&socketTimeoutMS=2000
  mysql:
    test:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password: